project:
  type: website
  output-dir: docs

website:
  title: "postcards"
  navbar:
    left:
      - href: postcards.qmd
        text: Postcards
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
