project:
  type: website


website:
  title: "postcards"
  navbar:
    left:
      - href: postcards.qmd
        text: postcards
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
